### ISSUE TITLE
Initial multicluster support

### ISSUE THREAD

**Issue by roee88** [IBM/the-mesh-for-data#134]
This is an umbrella issue for initial multicluster support

# Background

The multicluster support [design document](https://docs.google.com/document/d/1r5VLIqV07YharGTlaN7-Dbo33Mdy7AgEg29ArqmKSTo/edit?usp=sharing) describes long term plans for full multicluster support. This issue is a subset of it targeting a first milestone with limited scope.

# Scope

A first target milestone is set for supporting a specific simple scenario:
- User workload runs in one cluster
- Implicit copy job needs to run in a different cluster (performing transformations)
- Result of the implicit copy is accessible by the workload (e.g., through flight module)
- Both source and target storage for the implicit copy are object storage buckets. A bucket is currently physically external to a cluster, but virtually attached to it (same "scope" or geo-location).

# Design

Each sub-issue will have its own detailed design description. Here we sketch a high level design for _this_ milestone.

- A primary-remotes topology with a centralized control plane in the primary cluster and workloads (such as modules) running in either primary or remotes clusters. Remote clusters have egress connectivity to the primary cluster.
- [Razee](https://razee.io/) is used for deploying and monitoring the status of remote resources
- A single description of a multicluster blueprint is needed (even if just for auditing; not necessarily a CRD or persisted anywhere)
- In this milestone the M4DApplication and the user workload are assumed to be running on the primary cluster

# Sub issues

- [x] #135 Multicluster blueprint generation
- [x] #136 Multicluster blueprint orchestration
- [x] #144 Golang API for Multi-cluster env info
- [x] #145 Cluster identifier
- [x] #141 Multicluster kind setup
- [x] #149 Multicluster installation: Razee components
- [ ] Multicluster installation: M4D components
- [x] Support linking storage/dataset to a cluster scope

## Deferred

- [ ] M4DModule: add cluster dependencies to dependencies section
- [ ] Multicluster demo (with the opa, egeria, vault connectors stack)
- [ ] Grant access to dataset credentials to remote modules (temporary workaround for manual testing: expose secret-provider service)
- [ ] Update documentation with multicluster support (including cluster registration process)
- [ ] Multicluster integration test

**Comment by tomersolomon1** [comment]
@roee88 Plz add to the list above changes to the manager. For example something like:

**Comment by hunchback** [comment]
@roee88 / @tomersolomon1 reflections regarding deployment tool

IBM itself has many options: KubeFed (lead by RedHat), ACM (formally MCM lead by IBM), and Razee (part of Satellite).

KubeFed and ACM are the old generation of cluster manager which don't scale well and don't fit with the current trends of running many many small k8s clusters in the edge, possibly 1000s over more.

Razee seems like a much of repos and tools which are half-baked, and in its' current form appears like it will not be able to compete with other emerging solutions for multi-cluster management.

A tool which seems to be mature and suitable for modern multi-cluster k8s deployments is rancher fleet, its' setup is trivial, and it appears to be of a good quality (https://github.com/rancher/fleet.

Some pointers for comparison:
- razee a collections of nodejs repos vs fleet a single go repo
- razee 250 start / 25 folks / 1.5 years (https://www.ibm.com/cloud/blog/announcing-razee) vs. fleet 500+ starts / 50 forks / 0.5 a year (https://rancher.com/blog/2020/fleet-management-kubernetes/) - fleet gaining recognition 6x faster than razee
- razee has a long complex setup page (https://github.com/razee-io/Razee/blob/master/README.md) vs. fleet short trivial setup page (https://github.com/rancher/fleet/README.md)
- razee tested for on 10s/100s of node on IBM Cloud vs fleet tested on large scale use cases (https://rancher.com/blog/2020/scaling-fleet-kubernetes-million-clusters)

Especially as we are planning for a close integration with Razee, maybe we should reconsider and rather go with a leading offering. As if Razee does not pick up traction it will be abandoned regardless of if it come out of IBM or not ....

**Comment by roee88** [comment]
I believe that you attended the meeting where I presented the different options, including *all* of the tools that you mentioned, fleet included. 

To correct some of your assumptions:
1. We don't choose by what's IBM and what's not, we will embrace any good open solution.
2. We are not tied to Razee. Swapping it out and using something else in the future is definitely possible, even supporting multiple options as you can see in the comment for #136.
3. Razee is the target for this milestone because it's a tool that matches our requirements and we had the chance to experiment with it. Like fleet, it does scale to 1000s of clusters and is pull based so no need for egress from primary to remotes. Unlike fleet is doesn't require direct access to the API server from the remotes (which would require investigation to know if it's okay or not, considering authentication). @froesef and @tomersolomon1 are validating the feasibility of using Razee and we might need to investigate another option according to the outcome of their experimentation but so far it looks promising. 
4. I wouldn't declare kubefed nor acm as old generation, they are all evolving rapidly

**Comment by hunchback** [comment]
@roee88 w.r.t network connectivity of the clusters (realm of rancher submariner), do you have any initial thought ?

**Comment by froesef** [comment]
Closing this as the initial multicluster support is done and follow-up issues are created separately.
