### ISSUE TITLE
Epic proposal: dynamic taxonomy and a refined default plugins stack

### ISSUE THREAD

**Issue by roee88** [IBM/the-mesh-for-data#182]
DRAFT ISSUE

# Problem statement 

An end to end solution requires a taxonomy to be defined and used across different components. The Mesh for Data includes core components (mainly defined in `manager` and `pkg`) and plugins (`connectors` and `modules`). Currently, a partial but single _hardcoded_ taxonomy is defined across both core components and plugins. This creates a problem when working with tools that use a different taxonomy and support different features (e.g., a new datastore that we did not define).

# Taxonomy types

1. Actions (related: https://github.com/IBM/the-mesh-for-data/issues/65)
1. Connections, authentication methods and formats (related: https://github.com/IBM/the-mesh-for-data/issues/96)
1. Clusters (see https://github.com/IBM/the-mesh-for-data/issues/145)
1. Regions and zones (see https://github.com/IBM/the-mesh-for-data/issues/146)
1. Purposes
1. Roles

\* Not all types are to be defined by M4D/plugins stack (e.g., roles are a property of the catalog itself)

# Role of core components

The core components **must** be agnostic to the taxonomy. If we implement it right, we can have validation as a core feature in the future. For example, to alert when no module implements a declared action.

# Plugins stack

A plugins stack is a set of connectors and modules that work together. The current connectors stack that we use has a bit of an undesired complexity, implemented as if there are 3 different systems but actually tying them together using naming conventions (which works but without delivering the right message). Instead, we should think of it as a single harmonic stack that is attached to a stack-specific taxonomy. As part of this proposed epic I propose work to refine the connectors of our default stack by:
- [ ] https://github.com/IBM/the-mesh-for-data/issues/163 Replace Egeria with a simple demo catalog
- [ ] Use vault as an internal component of the demo catalog rather than as a first party
- [ ] Use a stack-defined taxonomy
- [ ] Remove hardcoded taxonomy from `pkg/connectors` and `manager`

Later, changes to tie modules to a taxonomy will also be needed, with the hope that with minor changes we can allow the same module to support different taxonomies just by creating a separate `M4DModule`.

---

Looking for feedback especially on taxonomy and for partners for a technical design of the plugins stack.

**Comment by roee88** [comment]
After initial discussion with @rohithdv and Ritwik we created initial grouping of the taxonomy to these types:
1. Actions
1. Connections (including formats and authentication methods)
1. Runtime metadata (purpose and roles are examples)
1. Clusters (and: regions, zones) - DEFERRED

The taxonomy should be defined in a single place but not as part of the control plane and not hardcoded. The control plane should be aware of the taxonomy mainly for linking actions and connections to modules. TBD how this can be done.

As for a plugin stack, we decided to iterate on what we have today starting with https://github.com/IBM/the-mesh-for-data/issues/163. Replacing it with something simple for quick evaluation at the cost of losing a real integration is not preferable.

**Comment by simanadler** [comment]
@roee88 @rohithdv Ritwik, I agree with the problem statement in general.  Some comments:

(1) I'm not sure though that some of the changes (ex: replace egaria) you want to do should be part of this issue.  

(2) We need to be careful about making the taxonomies connector dependent.  If the taxonomies change per connector  (ex: different catalog or different policy engine) then the modules will have to be per connector.  I'm not sure that's what we really want.  Right?

Ex: If policy manager A has a MaskXYZ action and policy manager B has a MaskABC action, and both do the same thing ... then does the module have to declare that it supports both?  If yes, then each time a new connector is created the modules have to be updated.  On the other hand, if M4D has an internal taxonomy to which the taxonomies of the connectors are mapped then the modules don't have to change.

(3) There needs to be a mechanism for defining and updating the taxonomies.  Where/how will this be done?  By which actor?  Where will the taxonomies be storied?  Will they have to be distributed across clusters?

**Comment by roee88** [comment]
I'll close this issue and open one dedicated to taxonomy. Before I do that, @simanadler can you provide a full description of your point of view on taxonomies given your past experience with it

**Comment by roee88** [comment]
Replaced with https://github.com/IBM/the-mesh-for-data/issues/238
