### ISSUE TITLE
Improve Helm charts

### ISSUE THREAD

**Issue by roee88** [IBM/the-mesh-for-data#348]
- [x] #351 CRDs generated directly to `charts/m4d-crd` (using controller-gen)
- [x] #368 RBAC not generated from annotations and instead maintained directly in `charts/m4d` (allows different RBAC for coordinator/remote as described in https://github.com/IBM/the-mesh-for-data/issues/304)
- [x] #364 Manager resources splitted to different files and use Helm recommend templating
- [x] https://github.com/IBM/the-mesh-for-data/pull/390 Generate webhook resources into the chart
- [x] configmap m4d-config is currently not part of the chart, should be added
- [x] configmap cluster-metadata is currently not part of the chart, should be added (only if razee is enabled?)
- [x] Profiles: coordinator, remote, ~~integration-tests~~ (https://github.com/IBM/the-mesh-for-data/issues/317)
- [x] #374 Integrate multi cluster setup
- [x] Flag to skip cluster scoped resouces (manager-auth-proxy-*, manager-cr, manager-crb, webhook-configs) or change the crd chart to base chart that includes all cluster scoped resources. @eletonia 
- [ ] #450 Add Istio resources when Istio is available
- [ ] Remove secret provider deployment
- [x] Rework OPA server deployment
- [ ] Remove kustomize config from manager 
- [ ] Change root Makefile to deploy with the charts
- [ ] Workflow for chart validation (See https://github.com/mesh-for-data/charts#2-add-github-workflow-for-testing-the-chart)
- [ ] Update developers docs 
- [ ] Set version 0.1.0 in charts
- [ ] Fine grained RBAC
- [ ] A direct way to disable motion controllers / to deploy just motion controllers (currently possible using manager.enable and manager.overrideArgs). Do we want a `motion` section next to `coordinator` and `worker`?
- [ ] Vault address without "m4d-system" in values.yaml

**Comment by roee88** [comment]
> Flag for applying all, cluster scoped only, or namespace scoped only

@eletonia will this meet the requirements for deploying to operate first?

**Comment by eletonia** [comment]
@roee88 Yes we should be able to use Helm parameters and override them with [ArgoCD parameters](https://argoproj.github.io/argo-cd/user-guide/helm/#helm-parameters) to make ArgoCD only deploy the namespace scoped resources

**Comment by roee88** [comment]
> What changes do we have in the helm chart that are not generated by controller-gen? I think we should try to generate as much as possible from the code. Manual editing of the crd files or similar may lead to inconsistencies. Maybe there are different tags that we can use in the go code to achieve similar things. Also I think we should drop the `CRD_OPTIONS` variable and put the parameter explicitly into the `controller-gen` call. That way it's clear what is generated at what point.

Let's break it down:

# CRDs

CRDs include a basic structure (group, kind, etc.):
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema: <intentionally missing>
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
```

They also include a schema (all types and structure)

They optionally also include conversion webhooks. 

There are also column printers, I'm not sure if they are part of schema or not, I will check and edit my message.

`controller-gen` includes two commands: `crd` for generating basic+schema, or `schemapatch` to generate just schema. The webhooks parts are always added later (not controller-gen's job). 

As long as we don't need conversion webhooks we can use the `crd` command to generate everything like in #351. Once we will need conversion webhooks, we will need to either move to `schemapatch` and add the webhooks stuff directly in Helm (like cert-manager does), or stick to `crd` and use kustomize to generate it into the chart (i.e., set namespace to the helm release namespace). 

Sticking to `crd` seems like a good approach because it generates more. I opted for doing it directly without kustomize because we don't have conversion webhooks yet, so it seems to meet current requirements and can be changed when conversion webhooks will be needed. However, any of these options is fine by me so @froesef feel free to give your choice here.

# RBAC

There is no real value in adding the rbac code comments and generating yaml from it. They both include exactly the same information and YAMLs are as easy to write if not easier. `controller-gen` is very opinionated here and would not allow us to fine tune RBAC like we need to (coordinator vs remote).

# Admission Webhooks

controller-gen is not flexible at all but I don't think we would want to avoid using it here.. I could only get it working using kustomize to generate webhooks.yaml into the charts which seems fine.

**Comment by roee88** [comment]
Summary of conversation with @froesef:
- Use `controller-gen crd` for CRDs and output them directly to the chart. When we get to a point that it doesn't meet our requirements we will change (if we get to that point, and based on what controller-gen will offer by then).
- Maintain RBAC directly in the chart
- It is desirable to remove the config folder completely but we don't have a clean solution to the admission webhooks yet.

**Comment by roee88** [comment]
Remaining items are opened as discussions or other issues.
